### ISSUE TITLE
Can I use data:image/png;base64, as SRC ?

### ISSUE THREAD

**Issue by jberthe** [can3p/iviewer#90]
Hello,
 
I have a requirement on my project. I do not have the image on my server, I download them during the runtime so I do not have the source path but only the Base64 encoded image.

How can I use your nice library for that ?

Regards

**Comment by can3p** [comment]
You can pass data uri to the image src setter, so you can just pass this data instead of src url to the plugin. The question is more about whether the proper image events like onload will fire. Can you try that?

**Comment by jberthe** [comment]
It works perfectly :)

Thanks a lot.
